package controllers;

public enum Command {
    C_ES_LANGUAGE,C_US_LANGUAGE,EXIT_APP,LOAD_FILE,SAVE_FILE,

    ADD_PATIENT,SEARCH_PATIENT,MODIFY_PATIENT,DELETE_PATIENT, REFRESH_DATA,

    C_MENU_HOME,C_MENU_TABLE,C_MENU_STATISTIC,C_MENU_ABOUT,

    C_ACTIVE_CASES,C_DEATH_CASES,C_RECOVERED_CASES,C_CASES_LOCATION,
    C_REPORT_LETHAL,C_REPORT_HEALTH,
    C_GRAPHICS_LINE,C_GRAPHICS_BAR,C_GRAPHICS_TORTE;


}
