package controllers;

public enum Command {
    C_ES_LANGUAGE,C_US_LANGUAGE,EXIT_APP,LOAD_FILE,SAVE_FILE,

    ADD_PATIENT,SEARCH_PATIENT,MODIFY_PATIENT,DELETE_PATIENT, REFRESH_DATA,

    C_RANGE_AGE_COL_DIAG, C_AGE_COL_DIAG, C_LETHALITY_COL_DEATH, C_MONTHS_COL_DEATH,
    C_RANGE_AGE_COL_RECO,C_AGE_COL_RECO,C_MONTHS_COL_RECO,

    C_RANGE_AGE_LOC_DIAG, C_AGE_LOC_DIAG, C_LETHALITY_LOC_DEATH, C_MONTHS_LOC_DEATH,
    C_RANGE_AGE_LOC_RECO,C_AGE_LOC_RECO,C_MONTHS_LOC_RECO,C_TABLE_LOC,
    C_GRAPHICS_MONTHS,C_GRAPHICS_BAR,C_GRAPHICS_TORTE,ABOUT_US,ABOUT_APP;

}
